#title in header
title: "小站"

#main info
#owner
owner: "Mett li"
email: xd842303863@163.com
info: "立志成为有趣的开发者。"
#description
# desc: ""

#menu 
# relative to themes/minima/source
menu:
  About: /About

#index/main page max show posts (in number)
max_post: 8

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
# placename: Earth
# placelink: https://en.wikipedia.org/wiki/Earth
# github: https://github.com/adisaktijrs
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
# thumbnail: /images/thumbnail.jpg

article:
  thumbnail: false

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
